version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_USER=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    expose:
      - "5672"
      - "15672"


volumes:
  rabbitmq:

